services :
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotyjukebox-user
      POSTGRES_PASSWORD: spotyjukebox-pass
      POSTGRES_DB: spotyjukebox
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - default
networks:
  default:
volumes:
  db-data: